# Generated by Django 5.2.4 on 2025-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodigitalsurveyorsapp", "0003_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
