# Generated by Django 5.2.4 on 2025-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodigitalsurveyorsapp", "0004_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
