# Generated by Django 5.2.4 on 2025-07-15 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodigitalsurveyorsapp", "0005_galleryimage_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="rating",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
