# Generated by Django 5.2.4 on 2025-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodigitalsurveyorsapp", "0006_remove_testimonial_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
