# Generated by Django 4.2.7 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodigitalsurveyorsapp", "0009_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "ip_address")},
        ),
    ]
